### ISSUE TITLE
Fix Kabsch algorithm (rigid alignment)

### ISSUE THREAD

**Issue by VincentBt** [shenoynikhil/ETFlow#11]
Hi! Thank you for this piece of work. I noticed a mistake in your rotation matrix computation (part of the Kabsch algorithm for alignment) [here](https://github.com/shenoynikhil/ETFlow/blob/main/etflow/models/utils.py#L247):
```
# Rotation matrix
R = V.mm(U.T)
```
should be replaced with
```
# Rotation matrix
R = V.mm(U.T)
# Ensure R is a proper rotation matrix
if torch.det(R) < 0:  # reflection
    V[:, -1] *= -1  # flip the sign of the last column of V
    R = V.mm(U.T)
```
See [this link](https://gist.github.com/bougui505/e392a371f5bab095a3673ea6f4976cc8) for justification

**Comment by shenoynikhil** [comment]
Thanks for looking into this and for the quick PR.
